<?php

namespace Database\Seeders;

use App\Models\MappingNatureOfImpact;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class MappingNatureOfImpactSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        MappingNatureOfImpact::insert([
            ['kode_profesi' => 'STR 1.1.1.1', 'jenis' => 'Share', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'STR 1.1.1.2', 'jenis' => 'Share', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'STR 1.1.1.3', 'jenis' => 'Share', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'STR 1.1.1.4', 'jenis' => 'Remote', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'TEK 1.1.2.1', 'jenis' => 'Non Quantifable', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'TEK 1.1.2.2', 'jenis' => 'Non Quantifable', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'TEK 1.1.2.3', 'jenis' => 'Non Quantifable', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'MAS 1.1.3.1', 'jenis' => 'Remote', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'MAS 1.1.3.2', 'jenis' => 'Remote', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'MPK 1.1.4.1', 'jenis' => 'Non Quantifable', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'MPK 1.1.4.2', 'jenis' => 'Non Quantifable', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'ENJ 1.2.1.1', 'jenis' => 'Share', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'ENJ 1.2.1.2', 'jenis' => 'Share', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'ENJ 1.2.1.3', 'jenis' => 'Share', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'ENJ 1.2.1.4', 'jenis' => 'Share', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'ENJ 1.2.1.5', 'jenis' => 'Share', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'ENJ 1.2.1.6', 'jenis' => 'Share', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'ENJ 1.2.1.7', 'jenis' => 'Share', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'ENJ 1.2.1.8', 'jenis' => 'Share', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'ENJ 1.2.1.9', 'jenis' => 'Non Quantifable', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'MPO 1.2.2.1', 'jenis' => 'Remote', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'MPO 1.2.2.2', 'jenis' => 'Remote', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'MPO 1.2.2.3', 'jenis' => 'Remote', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'MPO 1.2.2.4', 'jenis' => 'Remote', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'MPO 1.2.2.5', 'jenis' => 'Remote', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'MRP 1.3.1.1', 'jenis' => 'Remote', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'MRP 1.3.1.2', 'jenis' => 'Remote', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'MRP 1.3.1.3', 'jenis' => 'Remote', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'LIB 1.4.1.1', 'jenis' => 'Non Quantifable', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'LIB 1.4.1.2', 'jenis' => 'Non Quantifable', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'LIB 1.4.1.3', 'jenis' => 'Non Quantifable', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'LIB 1.4.1.4', 'jenis' => 'Non Quantifable', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'LIB 1.4.1.5', 'jenis' => 'Non Quantifable', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'LIB 1.4.1.6', 'jenis' => 'Non Quantifable', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'LIB 1.4.1.7', 'jenis' => 'Non Quantifable', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'UJK 1.4.2.1', 'jenis' => 'Non Quantifable', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'UJK 1.4.2.2', 'jenis' => 'Non Quantifable', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'UJK 1.4.2.3', 'jenis' => 'Non Quantifable', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'UJK 1.4.2.4', 'jenis' => 'Non Quantifable', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'SER 1.4.3.1', 'jenis' => 'Non Quantifable', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'SER 1.4.3.2', 'jenis' => 'Non Quantifable', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'SER 1.4.3.3', 'jenis' => 'Non Quantifable', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'PPK 1.4.4.1', 'jenis' => 'Non Quantifable', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'PPK 1.4.4.2', 'jenis' => 'Non Quantifable', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'PPK 1.4.4.3', 'jenis' => 'Non Quantifable', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'EPI 1.5.1.1', 'jenis' => 'Remote', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'EPI 1.5.1.2', 'jenis' => 'Remote', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'EPI 1.5.1.3', 'jenis' => 'Remote', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'EPI 1.5.1.4', 'jenis' => 'Remote', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'EPI 1.5.1.5', 'jenis' => 'Remote', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'PKT 1.5.2.1', 'jenis' => 'Share', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'PKT 1.5.2.2', 'jenis' => 'Share', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'PKT 1.5.2.3', 'jenis' => 'Share', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'PKT 1.5.2.4', 'jenis' => 'Share', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'PKT 1.5.2.5', 'jenis' => 'Share', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'PKT 1.5.2.6', 'jenis' => 'Share', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'OPS 1.6.1.1', 'jenis' => 'Share', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'OPS 1.6.1.2', 'jenis' => 'Share', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'OPS 1.6.1.3', 'jenis' => 'Share', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'OPS 1.6.1.4', 'jenis' => 'Share', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'OPS 1.6.1.5', 'jenis' => 'Share', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'FSO 1.6.2.1', 'jenis' => 'Share', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'FSO 1.6.2.2', 'jenis' => 'Share', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'FSO 1.6.2.3', 'jenis' => 'Share', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'FSO 1.6.2.4', 'jenis' => 'Share', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'MER 1.8.1.1', 'jenis' => 'Share', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'MER 1.8.1.2', 'jenis' => 'Share', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'MER 1.8.1.3', 'jenis' => 'Share', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'MER 1.8.1.4', 'jenis' => 'Share', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'MER 1.8.1.5', 'jenis' => 'Share', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'SDM 2.1.1.1', 'jenis' => 'Non Quantifable', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'SDM 2.1.1.2', 'jenis' => 'Non Quantifable', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'SDM 2.1.1.3', 'jenis' => 'Non Quantifable', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'SDM 2.1.1.4', 'jenis' => 'Non Quantifable', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'SDM 2.1.1.5', 'jenis' => 'Non Quantifable', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'SDM 2.1.1.6', 'jenis' => 'Non Quantifable', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'PBR 2.1.2.1', 'jenis' => 'Non Quantifable', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'PBR 2.1.2.2', 'jenis' => 'Non Quantifable', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'PBR 2.1.2.3', 'jenis' => 'Non Quantifable', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'PBR 2.1.2.4', 'jenis' => 'Non Quantifable', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'TIF 2.2.1.1', 'jenis' => 'Remote', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'TIF 2.2.1.2', 'jenis' => 'Remote', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'TIF 2.2.1.3', 'jenis' => 'Remote', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'TEL 2.2.2.1', 'jenis' => 'Remote', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'TEL 2.2.2.2', 'jenis' => 'Remote', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'TEL 2.2.2.3', 'jenis' => 'Remote', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'KEU 2.3.1.1', 'jenis' => 'Remote', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'KEU 2.3.1.2', 'jenis' => 'Remote', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'KEU 2.3.1.3', 'jenis' => 'Remote', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'KEU 2.3.1.4', 'jenis' => 'Non Quantifable', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'KEU 2.3.1.5', 'jenis' => 'Remote', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'ARK 2.4.1.1', 'jenis' => 'Non Quantifable', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'ARK 2.4.1.2', 'jenis' => 'Non Quantifable', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'ARK 2.4.1.3', 'jenis' => 'Non Quantifable', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'HKK 2.4.2.1', 'jenis' => 'Non Quantifable', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'HKK 2.4.2.2', 'jenis' => 'Non Quantifable', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'KOM 2.5.1.1', 'jenis' => 'Non Quantifable', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'KOM 2.5.1.2', 'jenis' => 'Non Quantifable', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'KOM 2.5.1.3', 'jenis' => 'Non Quantifable', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'MPU 2.5.2.1', 'jenis' => 'Non Quantifable', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'MPU 2.5.2.2', 'jenis' => 'Remote', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'K3L 2.6.1.1', 'jenis' => 'Non Quantifable', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'K3L 2.6.1.2', 'jenis' => 'Non Quantifable', 'created_by' => 'Iqbal.Chandra'],
            ['kode_profesi' => 'K3L 2.6.1.3', 'jenis' => 'Non Quantifable', 'created_by' => 'Iqbal.Chandra']
        ]);
    }
}
