<?php

namespace Database\Seeders;

use App\Models\PokoUtamaGenerik;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PokoUtamaGenerikSeeder extends Seeder
{
    /**
     * php artisan db:seed --class=PokoUtamaGenerikSeeder
     */
    public function run(): void
    {
        PokoUtamaGenerik::insert([
        ['jenis_jabatan' => 'fungsional', 'aktivitas' => 'Mematuhi dan melaksanakan seluruh program perusahaan yang meliputi, namun tidak terbatas pada manajemen risiko (mulai dari proses identifikasi, analisa, evaluasi, mitigasi risiko, monitoring risiko beserta pelaporannya), manajemen aset, improvement unit kerja (OPI), budaya dan program pengembangan human capital, K3, keamanan dan lingkungan, 5S, Sistem Manajemen Terpadu (IPIMS) serta program efisiensi energi dan Knowledge Sharing (menyampaikan pengetahuan sesuai kompetensinya melalui metode mengajar/menulis/merekam/metode lainnya), environment, social, dan governance (“ESG”) termasuk di dalamnya pengarusutamaan gender sesuai dengan kewenangannya di unit kerja masing-masing.', 'output' => '	Dokumen Laporan Pelaksanaan Program Perusahaan'	, 'jenis' => 'generik', 'created_by' => 'iqbal.chandra'	],
        ['jenis_jabatan' => 'fungsional', 'aktivitas' => 'Melakukan pelaporan kegiatan fungsi kerja yang menjadi tanggung jawabnya dengan menyusun laporan rutin dan non rutin yang diatur oleh Perusahaan baik secara manual maupun pada aplikasi korporat (ERP, ERM, CSA-ICoFR dan sebagainya) untuk menjamin ketersediaan informasi terkait kegiatan kerja dan fungsinya.', 'output' => '	Laporan Pekerjaan Bidang dan/atau Sub Bidang baik secara manual maupun pada aplikasi korporat'	, 'jenis' => 'generik', 'created_by' => 'iqbal.chandra'	],
        ['jenis_jabatan' => 'fungsional', 'aktivitas' => 'Mematuhi seluruh ketentuan Kebijakan Anti Penyuapan dan Kebijakan terkait Penyuapan lainnya (Kebijakan Pengendalian Gratifikasi, Kebijakan Whistleblower, Kebijakan Benturan Kepentingan, Kebijakan Indonesia Power Bersih, Kode Etik, Kebijakan Keterbukaan Informasi Publik, dan Kebijakan Good Corporate Governance), menjalankan tanggung jawab pekerjaan dan tugas secara etis, jujur, rajin dan selalu waspada serta siap melaporkan setiap kasus dugaan suap dengan segera, serta berpartisipasi aktif dalam pelatihan Anti Penyuapan sesuai yang dipersyaratkan dalam peran dan tanggung jawab jabatannya.	', 'output' => '	Laporan pelaksanaan kegiatan Anti Penyuapan (jika ada)'	, 'jenis' => 'generik', 'created_by' => 'iqbal.chandra'	],
        ['jenis_jabatan' => 'fungsional', 'aktivitas' => 'Melaksanakan pengendalian data pribadi terkait proses bisnis pada masing-masing Bagian/Bidang/Satuansesuai dengan regulasi internal maupun eksternal sesuai yang dipersyaratkan dalam peran dan tanggung jawab jabatannya.	', 'output' => '	Laporan pelaksanaan kegiatan pengendalian data pribadi (jika ada)'	, 'jenis' => 'generik', 'created_by' => 'iqbal.chandra'	],
        ['jenis_jabatan' => 'struktural', 'aktivitas' => 'Mengelola rencana kerja anggaran Bagian/Bidang/Satuan dengan merencanakan, memonitor dan mengendalikannya agar selaras dengan anggaran korporat dan rencana kerja Bagian/Bidang/Satuan untuk mendukung RJP Perusahaan dan RKA Perusahaan	', 'output' => '	Dokumen RKA Bidang dan/atau Sub Bidang'	, 'jenis' => 'generik', 'created_by' => 'iqbal.chandra'	],
        ['jenis_jabatan' => 'struktural', 'aktivitas' => 'Mengelola seluruh program perusahaan yang meliputi, namun tidak terbatas pada manajemen risiko (mulai dari proses identifikasi, analisa, evaluasi, mitigasi risiko, monitoring risiko beserta pelaporannya), manajemen aset, improvement unit kerja (OPI), budaya dan program pengembangan human capital, K3, keamanan dan lingkungan, 5S, Sistem Manajemen Terpadu (IPIMS) serta program efisiensi energi dan Coaching-Mentoring-Counseling termasuk Knowledge Sharing (menyampaikan pengetahuan sesuai kompetensinya melalui metode mengajar/menulis/merekam/metode lainnya), environment, social, dan governance (“ESG”) termasuk di dalamnya pengarusutamaan gender; sesuai dengan kewenangannya di unit kerja masing-masing.	', 'output' => '	"Dokumen perencanaan, pelaksanaan, dan evaluasi atas program Perusahaan"'	, 'jenis' => 'generik', 'created_by' => 'iqbal.chandra'	],
        ['jenis_jabatan' => 'struktural', 'aktivitas' => 'Melakukan pelaporan kegiatan fungsi kerja yang menjadi tanggung jawabnya dengan menyusun laporan rutin dan non rutin yang diatur oleh Perusahaan baik secara manual maupun pada aplikasi korporat (ERP, ERM, CSA-ICoFR dan sebagainya) untuk menjamin ketersediaan informasi terkait kegiatan kerja dan fungsinya.	', 'output' => '	Laporan Pekerjaan Bidang dan/atau Sub Bidang baik secara manual maupun pada aplikasi korporat'	, 'jenis' => 'generik', 'created_by' => 'iqbal.chandra'	],
        ['jenis_jabatan' => 'struktural', 'aktivitas' => 'Mematuhi seluruh ketentuan Kebijakan Anti Penyuapan dan Kebijakan terkait Penyuapan lainnya (Kebijakan Pengendalian Gratifikasi, Kebijakan Whistleblower, Kebijakan Benturan Kepentingan, Kebijakan Indonesia Power Bersih, Kode Etik, Kebijakan Keterbukaan Informasi Publik, dan Kebijakan Good Corporate Governance), menjalankan tanggung jawab pekerjaan dan tugas secara etis, jujur, rajin dan selalu waspada serta siap melaporkan setiap kasus dugaan suap dengan segera, serta berpartisipasi aktif dalam pelatihan Anti Penyuapan sesuai yang dipersyaratkan dalam peran dan tanggung jawab jabatannya.	', 'output' => '	Laporan pelaksanaan kegiatan Anti Penyuapan (jika ada)'	, 'jenis' => 'generik', 'created_by' => 'iqbal.chandra'	],
        ['jenis_jabatan' => 'struktural', 'aktivitas' => 'Memberikan dukungan resource untuk pengembangan bisnis perusahaan sesuai dengan tanggung jawabnya dalam rangka mendukung pencapaian pendapatan beyond kWh dan transisi energi green power plant termasuk peningkatan awareness to optimization dalam pengelolaan bisnis Perusahaan	', 'output' => '	Pegawai berkontribusi mendukung pengembangan bisnis (Man Hours)'	, 'jenis' => 'generik', 'created_by' => 'iqbal.chandra'	],
        ['jenis_jabatan' => 'struktural', 'aktivitas' => 'Melaksanakan pengendalian data pribadi terkait proses bisnis pada masing-masing Bagian/Bidang/Satuansesuai dengan regulasi internal maupun eksternal sesuai yang dipersyaratkan dalam peran dan tanggung jawab jabatannya.',  'output' => '	Laporan pelaksanaan kegiatan pengendalian data pribadi (jika ada)'	, 'jenis' => 'generik', 'created_by' => 'iqbal.chandra'	],

        ]);
    }
}
